"""Constants for the Ufanet Intercom integration."""

DOMAIN = "ufanet_intercom"
INTEGRATION_VERSION = "0.19.1"

UFANET_BASE_URL = "https://dom.ufanet.ru"
UCAMS_BASE_URL = "https://cloud.ucams.ru"
UCAMS_TOKEN_TTL = 20800

CONF_USERNAME = "username"
CONF_PASSWORD = "password"

CONF_SKUD_SCAN_INTERVAL = "skud_scan_interval_seconds"
CONF_CALL_SCAN_INTERVAL = "call_scan_interval_seconds"
CONF_MEDIA_REFRESH_INTERVAL = "call_media_refresh_seconds"
CONF_CALL_LEAD_SECONDS = "call_lead_seconds"
CONF_CALL_AUTOSAVE_ENABLED = "call_autosave_enabled"
CONF_CALL_AUTOSAVE_AFTER_SECONDS = "call_autosave_after_seconds"
CONF_ARCHIVE_DEFAULT_DURATION = "archive_default_duration_seconds"
CONF_ARCHIVE_DEFAULT_STEP = "archive_default_step_seconds"
CONF_EXPORT_DEFAULT_DURATION = "export_default_duration_seconds"
CONF_EXPORT_RETENTION_DAYS = "export_retention_days"
CONF_EXPORT_MAX_TOTAL_MB = "export_max_total_mb"
CONF_EXPORT_AUTO_CLEANUP = "export_auto_cleanup"

DEFAULT_SCAN_INTERVAL_SECONDS = 300
CALL_SCAN_INTERVAL_SECONDS = 10
MEDIA_REFRESH_SECONDS = 1800

EVENT_INTERCOM_CALL = "ufanet_intercom_call"

PLATFORMS = ["button", "camera", "datetime", "number", "sensor"]

SERVICE_GET_SETTINGS = "get_settings"
SERVICE_GET_RUNTIME_STATUS = "get_runtime_status"
SERVICE_GET_ARCHIVE_RANGES = "get_archive_ranges"
SERVICE_GET_ARCHIVE_URL = "get_archive_url"
SERVICE_GET_ARCHIVE_DOWNLOAD_URL = "get_archive_download_url"
SERVICE_LIST_ARCHIVE_EXPORTS = "list_archive_exports"
SERVICE_DELETE_ARCHIVE_EXPORT = "delete_archive_export"
SERVICE_CLEANUP_ARCHIVE_EXPORTS = "cleanup_archive_exports"
SERVICE_GET_CALL_EVENTS = "get_call_events"
SERVICE_GET_GUEST_ACCESS = "get_guest_access"
SERVICE_CREATE_GUEST_INVITE = "create_guest_invite"
SERVICE_FORGET_GUEST_INVITE = "forget_guest_invite"
SERVICE_REVOKE_SHARED_ACCESS = "revoke_shared_access"
SERVICE_CREATE_TEMPORARY_GUEST_LINK = "create_temporary_guest_link"
SERVICE_REVOKE_TEMPORARY_GUEST_LINK = "revoke_temporary_guest_link"

DEFAULT_ARCHIVE_DURATION_SECONDS = 300
MAX_ARCHIVE_DURATION_SECONDS = 21600

DEFAULT_ARCHIVE_STEP_SECONDS = 60

DEFAULT_EXPORT_RETENTION_DAYS = 30
DEFAULT_EXPORT_MAX_TOTAL_MB = 5120
MAX_EXPORT_RETENTION_DAYS = 3650
MAX_EXPORT_TOTAL_MB = 1048576

DEFAULT_CALL_LEAD_SECONDS = 15
DEFAULT_EXPORT_DEFAULT_DURATION_SECONDS = 300
DEFAULT_EXPORT_AUTO_CLEANUP = True

MIN_SKUD_SCAN_INTERVAL_SECONDS = 30
MAX_SKUD_SCAN_INTERVAL_SECONDS = 3600
MIN_CALL_SCAN_INTERVAL_SECONDS = 5
MAX_CALL_SCAN_INTERVAL_SECONDS = 300
MIN_MEDIA_REFRESH_SECONDS = 60
MAX_MEDIA_REFRESH_SECONDS = 7200

DEFAULT_CALL_AUTOSAVE_ENABLED = False
DEFAULT_CALL_AUTOSAVE_AFTER_SECONDS = 45
MAX_CALL_AUTOSAVE_AFTER_SECONDS = 600
CALL_AUTOSAVE_SETTLE_SECONDS = 12
CALL_AUTOSAVE_RETRY_SECONDS = 15
CALL_AUTOSAVE_RETRIES = 3
CALL_AUTOSAVE_RECOVERY_WINDOW_SECONDS = 300
