"""Optional configuration for Ufanet Intercom."""

from __future__ import annotations

from typing import Any

from homeassistant.config_entries import ConfigEntry

from .const import (
    CALL_SCAN_INTERVAL_SECONDS,
    CONF_ARCHIVE_DEFAULT_DURATION,
    CONF_ARCHIVE_DEFAULT_STEP,
    CONF_CALL_LEAD_SECONDS,
    CONF_CALL_AUTOSAVE_ENABLED,
    CONF_CALL_AUTOSAVE_AFTER_SECONDS,
    CONF_CALL_SCAN_INTERVAL,
    CONF_EXPORT_AUTO_CLEANUP,
    CONF_EXPORT_DEFAULT_DURATION,
    CONF_EXPORT_MAX_TOTAL_MB,
    CONF_EXPORT_RETENTION_DAYS,
    CONF_MEDIA_REFRESH_INTERVAL,
    CONF_SKUD_SCAN_INTERVAL,
    DEFAULT_ARCHIVE_DURATION_SECONDS,
    DEFAULT_ARCHIVE_STEP_SECONDS,
    DEFAULT_EXPORT_AUTO_CLEANUP,
    DEFAULT_EXPORT_DEFAULT_DURATION_SECONDS,
    DEFAULT_EXPORT_MAX_TOTAL_MB,
    DEFAULT_EXPORT_RETENTION_DAYS,
    DEFAULT_CALL_LEAD_SECONDS,
    DEFAULT_CALL_AUTOSAVE_ENABLED,
    DEFAULT_CALL_AUTOSAVE_AFTER_SECONDS,
    DEFAULT_SCAN_INTERVAL_SECONDS,
    MEDIA_REFRESH_SECONDS,
)

DEFAULT_OPTIONS: dict[str, Any] = {
    CONF_SKUD_SCAN_INTERVAL: DEFAULT_SCAN_INTERVAL_SECONDS,
    CONF_CALL_SCAN_INTERVAL: CALL_SCAN_INTERVAL_SECONDS,
    CONF_MEDIA_REFRESH_INTERVAL: MEDIA_REFRESH_SECONDS,
    CONF_CALL_LEAD_SECONDS: DEFAULT_CALL_LEAD_SECONDS,
    CONF_CALL_AUTOSAVE_ENABLED: DEFAULT_CALL_AUTOSAVE_ENABLED,
    CONF_CALL_AUTOSAVE_AFTER_SECONDS: DEFAULT_CALL_AUTOSAVE_AFTER_SECONDS,
    CONF_ARCHIVE_DEFAULT_DURATION: DEFAULT_ARCHIVE_DURATION_SECONDS,
    CONF_ARCHIVE_DEFAULT_STEP: DEFAULT_ARCHIVE_STEP_SECONDS,
    CONF_EXPORT_DEFAULT_DURATION: DEFAULT_EXPORT_DEFAULT_DURATION_SECONDS,
    CONF_EXPORT_RETENTION_DAYS: DEFAULT_EXPORT_RETENTION_DAYS,
    CONF_EXPORT_MAX_TOTAL_MB: DEFAULT_EXPORT_MAX_TOTAL_MB,
    CONF_EXPORT_AUTO_CLEANUP: DEFAULT_EXPORT_AUTO_CLEANUP,
}


def effective_options(entry: ConfigEntry) -> dict[str, Any]:
    """Return defaults merged with persisted ConfigEntry options."""
    return {**DEFAULT_OPTIONS, **dict(entry.options)}
